name: testing
on:
  workflow_dispatch
env:
  cloud: aws-cloud
jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: "Say my name u goddam right"
        run: echo "$greeting $first_name is using $cloud"
        env:
          first_name: srikanth
